using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Managed3D.Geometry;

namespace Managed3D.Rendering.Software
{
    /// <summary>
    /// Reprents a fragment generated by a fragment shader.
    /// </summary>
    public struct Fragment
    {
        #region Fields
        public Vector3 Position;
        public Vector4f Color;

        #endregion
        #region Methods

        #endregion
    }
}
